export const jobs = [
  {
    name: "Student Engineer",
    company: "Medsoft Technologies",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 15,
  },
  {
    name: "Systems Engineer",
    company: "Airforce Material Command ",
    type: "studentTrainee",
    currentlyHiring: true,
    location: "Bremerton, Washington",
    salary: 39,
  },
  {
    name: "Engineering Equipment Operator",
    company: "TACOM",
    type: "studentTrainee",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 21,
  },
  {
    name: "Student Engineer",
    company: "Unilever",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 17,
  },
  {
    name: "Customer Service Agent",
    company: "Acro sports",
    type: "studentTrainee",
    currentlyHiring: true,
    location: "Bremerton, Washington",
    salary: 16,
  },
  {
    name: "Network Operations Engineer",
    company: "Semtech",
    type: "partTime",
    currentlyHiring: false,
    location: "Burlington ON Canada",
    salary: 21,
  },
  {
    name: "Production Intern",
    company: "Trevor",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 15,
  },
];
