export const jobs = [
  {
    name: "Student Engineer",
    company: "Medsoft Technologies",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 15,
  },
  {
    name: "Student Engineer",
    company: "Medsoft Technologies",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 15,
  },
  {
    name: "Student Engineer",
    company: "Medsoft Technologies",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 15,
  },
  {
    name: "Student Engineer",
    company: "Medsoft Technologies",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 15,
  },
  {
    name: "Student Engineer",
    company: "Medsoft Technologies",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 15,
  },
  {
    name: "Student Engineer",
    company: "Medsoft Technologies",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 15,
  },
  {
    name: "Student Engineer",
    company: "Medsoft Technologies",
    type: "partTime",
    currentlyHiring: true,
    location: "Chicago Illinois USA",
    salary: 15,
  },
];
